// "use-client";
import AddPet from "./AddPet";
import BtnTest from "./BtnTest";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";

export const metadata = {
  title: "Pets Page",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col items-center">
          <div className="text-white text-2xl">Pets Page</div>
          {/* <BtnTest /> */}
          {session && session.user && <div className="text-white">Welcome {session.user.email}</div>}
          <AddPet />
          {children}
        </main>
      </body>
    </html>
  );
}
